支持邮箱推送二维码
huanghyw/jd_seckill pull request #218
Opened 2020-12-29 09:29 UTC by Joenothing-lst

2020-12-29 10:58 UTC, huanghyw commented
这个功能是为了能够在纯命令行上面进行扫码登录吗

2020-12-29 11:05 UTC, Joenothing-lst commented
> 这个功能是为了能够在纯命令行上面进行扫码登录吗

是的。
当然，也可以通过这个邮箱来推送抢购结果。
目前QQ邮箱是通过测试了，别的暂时没试过。

2020-12-29 14:23 UTC, huanghyw requested changes

2020-12-29 14:23 UTC, huanghyw commented on util.py
> +            print(f'邮箱登录失败: {e}')
这块改成用log打印

2020-12-29 14:23 UTC, huanghyw commented on util.py
> +                print(e)
log打印

2020-12-29 14:23 UTC, huanghyw commented on util.py
> +            print('邮箱未登录')
log打印

2020-12-29 14:23 UTC, huanghyw commented on util.py
> +    )
文件末尾加一个空行

2020-12-29 14:25 UTC, huanghyw commented
> > 这个功能是为了能够在纯命令行上面进行扫码登录吗
> 
> 是的。
> 当然，也可以通过这个邮箱来推送抢购结果。
> 目前QQ邮箱是通过测试了，别的暂时没试过。

可以，正好好多人说纯命令行下不能看二维码。
代码挺好，再微调一下。

2020-12-30 01:25 UTC, huanghyw approved these changes

2020-12-30 01:27 UTC, merged