Create jd_spider_requests.py
huanghyw/jd_seckill pull request #239
Opened 2020-12-29 14:36 UTC by pigZ-27

解决《预约失败，您已超出最多购买数量，谢谢惠顾！》情况，不一定预约成功

2020-12-30 01:52 UTC, huanghyw requested changes

2020-12-30 01:52 UTC, huanghyw commented on jd_spider_requests.py
> +                logger.info(reserve_reslut)
获取后的内容处理一下，i标签和空白都去掉吧。

![image](https://user-images.githubusercontent.com/7189743/103324532-dbdf9900-4a82-11eb-82e1-8281b64e93f5.png)

2020-12-30 05:00 UTC, pigZ-27 commented on jd_spider_requests.py
> +                logger.info(reserve_reslut)
已解决

2020-12-30 05:07 UTC, closed without merging

2020-12-30 05:19 UTC, pigZ-27 commented
大佬还继续么？
问题已解决，但是小弟已删代码了
这个传播太广了，现在自媒体太强大了，导致各自骗子横行，小心引火上身




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 上午9:52
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"_謨離"<596618679@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] 解决预约超出最多购买数量问题 (#239)





 
@huanghyw requested changes on this pull request.
 
 
In jd_spider_requests.py:
 &gt; @@ -379,11 +379,13 @@ def make_reserve(self):          self.timers.start()          while True:              try: -                self.session.get(url='https:' + reserve_url) -                logger.info('预约成功，已获得抢购资格 / 您已成功预约过了，无需重复预约') +                """解决《预约失败，您已超出最多购买数量，谢谢惠顾！》情况，不一定预约成功""" +                resp = self.session.get(url='https:' + reserve_url).content +                x_data = etree.HTML(resp) +                reserve_reslut = x_data.xpath("//p[@class='bd-right-result']/text()") +                logger.info(reserve_reslut)  
获取后的内容处理一下，i标签和空白都去掉吧。
 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-31 02:14 UTC, fy8207345 commented
抢购之前，需要开通plus会员吗？