需要登陆时命令行直接输出二维码
huanghyw/jd_seckill pull request #399
Opened 2020-12-31 09:33 UTC by alecthw

2020-12-31 09:48 UTC, huanghyw requested changes

2020-12-31 09:48 UTC, huanghyw commented on requirements.txt
> +pyzbar==0.1.8
本地如果没有装zbar-tool这个库貌似有问题，需要兼容一下这种情况

2020-12-31 10:37 UTC, alecthw commented
没注意还要额外库，我重新处理下

2020-12-31 10:37 UTC, closed without merging

2020-12-31 14:20 UTC, huanghyw commented
好嘞，多谢哈

2021-01-01 14:55 UTC, imageslr commented
或许这里执行的命令不是 README 里的，我执行的时候提示 `invalid opiton: -r`。

下面这个可以：

```
 zbarimg qr_code.png > qrcode.txt && qrencode -o - -t UTF8 < qrcode.txt
```

2021-01-05 08:55 UTC, luzihang123 commented
> 或许这里执行的命令不是 README 里的，我执行的时候提示 `invalid opiton: -r`。
> 
> 下面这个可以：
> 
> ```
>  zbarimg qr_code.png > qrcode.txt && qrencode -o - -t UTF8 < qrcode.txt
> ```
我也发现了，提了个pr
https://github.com/huanghyw/jd_seckill/pull/425

2021-01-05 09:07 UTC, alecthw commented
想找个不依赖外部库的python库直接输出二维码，还真没找到，太难了……