软件自动结束运行的条件增加
huanghyw/jd_seckill pull request #410
Opened 2021-01-03 06:56 UTC by wwwyeeting

根据config.ini文件中设置的stop_time来停止task的运行。
注意：此项修改暂未在正式抢购中测试使用，只在仿真下测试代码运行逻辑。

2021-01-03 07:24 UTC, huanghyw requested changes
这样就需要设置两个时间，太麻烦了。
不过可以考虑设置一个抢购时长，分钟为单位。

2021-01-03 07:36 UTC, wwwyeeting commented
> 这样就需要设置两个时间，太麻烦了。
> 不过可以考虑设置一个抢购时长，分钟为单位。

其实真的还好……
start_time跟stop_time的日期是一样的，具体的时间理论上5分钟就差不多了，只需要每次修改start_time的日期时同时修改stop_time即可。
在软件中强制加上结束时间也可以的，代码上改的不多。
`stop_time = datetime.strptime(global_config.getRaw('config','stop_time'), "%Y-%m-%d %H:%M:%S.%f")`
上面这句改为获取start_time，同时加上偏移值即可了。
我个人习惯是将配置项直接拉出来的，你也可以把运行时间放到配置文件中。这样做后面搞GUI会方便很多。

2021-01-03 08:37 UTC, huanghyw commented
> > 这样就需要设置两个时间，太麻烦了。
> > 不过可以考虑设置一个抢购时长，分钟为单位。
> 
> 其实真的还好……
> start_time跟stop_time的日期是一样的，具体的时间理论上5分钟就差不多了，只需要每次修改start_time的日期时同时修改stop_time即可。
> 在软件中强制加上结束时间也可以的，代码上改的不多。
> `stop_time = datetime.strptime(global_config.getRaw('config','stop_time'), "%Y-%m-%d %H:%M:%S.%f")`
> 上面这句改为获取start_time，同时加上偏移值即可了。
> 我个人习惯是将配置项直接拉出来的，你也可以把运行时间放到配置文件中。这样做后面搞GUI会方便很多。

过几天开始时间就去掉了，自动获取开始抢购时间，结束时间按照抢购时长来处理。
比如默认配置5分钟，就会在五分钟后结束抢购。

2021-01-03 09:19 UTC, abasefive commented
> > > 这样就需要设置两个时间，太麻烦了。
> > > 不过可以考虑设置一个抢购时长，分钟为单位。
> > 
> > 
> > 其实真的还好……
> > start_time跟stop_time的日期是一样的，具体的时间理论上5分钟就差不多了，只需要每次修改start_time的日期时同时修改stop_time即可。
> > 在软件中强制加上结束时间也可以的，代码上改的不多。
> > `stop_time = datetime.strptime(global_config.getRaw('config','stop_time'), "%Y-%m-%d %H:%M:%S.%f")`
> > 上面这句改为获取start_time，同时加上偏移值即可了。
> > 我个人习惯是将配置项直接拉出来的，你也可以把运行时间放到配置文件中。这样做后面搞GUI会方便很多。
> 
> 过几天开始时间就去掉了，自动获取开始抢购时间，结束时间按照抢购时长来处理。
> 比如默认配置5分钟，就会在五分钟后结束抢购。

太靠谱了

2021-01-03 10:44 UTC, jackquan commented
怎么考虑抢购IP封杀的处理

2021-01-03 11:35 UTC, ZRT-1998 commented
和UA的关系大吗,我现在想用随机的UA了,已经很久没有抢中了

2021-01-03 11:36 UTC, abasefive commented
> 怎么考虑抢购IP封杀的处理

走代理，或者部署到云计算服务-弹性容器实例

2021-01-03 11:37 UTC, ZRT-1998 commented
容器能虚拟出不同的IP吗?

2021-01-03 12:28 UTC, kevin-garrnet-hh commented
> 
> 
> > > 这样就需要设置两个时间，太麻烦了。
> > > 不过可以考虑设置一个抢购时长，分钟为单位。
> > 
> > 
> > 其实真的还好……
> > start_time跟stop_time的日期是一样的，具体的时间理论上5分钟就差不多了，只需要每次修改start_time的日期时同时修改stop_time即可。
> > 在软件中强制加上结束时间也可以的，代码上改的不多。
> > `stop_time = datetime.strptime(global_config.getRaw('config','stop_time'), "%Y-%m-%d %H:%M:%S.%f")`
> > 上面这句改为获取start_time，同时加上偏移值即可了。
> > 我个人习惯是将配置项直接拉出来的，你也可以把运行时间放到配置文件中。这样做后面搞GUI会方便很多。
> 
> 过几天开始时间就去掉了，自动获取开始抢购时间，结束时间按照抢购时长来处理。
> 比如默认配置5分钟，就会在五分钟后结束抢购。

老哥，到最后一步解码出二维码，扫不上....

2021-01-03 12:32 UTC, huanghyw commented
> 和UA的关系大吗,我现在想用随机的UA了,已经很久没有抢中了

最好还是别随机ua，过段时间自己换一个也行

2021-01-03 12:33 UTC, huanghyw commented
> > > > 这样就需要设置两个时间，太麻烦了。
> > > > 不过可以考虑设置一个抢购时长，分钟为单位。
> > > 
> > > 
> > > 其实真的还好……
> > > start_time跟stop_time的日期是一样的，具体的时间理论上5分钟就差不多了，只需要每次修改start_time的日期时同时修改stop_time即可。
> > > 在软件中强制加上结束时间也可以的，代码上改的不多。
> > > `stop_time = datetime.strptime(global_config.getRaw('config','stop_time'), "%Y-%m-%d %H:%M:%S.%f")`
> > > 上面这句改为获取start_time，同时加上偏移值即可了。
> > > 我个人习惯是将配置项直接拉出来的，你也可以把运行时间放到配置文件中。这样做后面搞GUI会方便很多。
> > 
> > 
> > 过几天开始时间就去掉了，自动获取开始抢购时间，结束时间按照抢购时长来处理。
> > 比如默认配置5分钟，就会在五分钟后结束抢购。
> 
> 老哥，到最后一步解码出二维码，扫不上....

换一个图片查看器，白色背景就可以

2021-01-03 12:34 UTC, wwwyeeting commented
> > > 这样就需要设置两个时间，太麻烦了。
> > > 不过可以考虑设置一个抢购时长，分钟为单位。
> > 
> > 
> > 其实真的还好……
> > start_time跟stop_time的日期是一样的，具体的时间理论上5分钟就差不多了，只需要每次修改start_time的日期时同时修改stop_time即可。
> > 在软件中强制加上结束时间也可以的，代码上改的不多。
> > `stop_time = datetime.strptime(global_config.getRaw('config','stop_time'), "%Y-%m-%d %H:%M:%S.%f")`
> > 上面这句改为获取start_time，同时加上偏移值即可了。
> > 我个人习惯是将配置项直接拉出来的，你也可以把运行时间放到配置文件中。这样做后面搞GUI会方便很多。
> 
> 过几天开始时间就去掉了，自动获取开始抢购时间，结束时间按照抢购时长来处理。
> 比如默认配置5分钟，就会在五分钟后结束抢购。

可以的。
我这边把接口写好，用的时候把开始时间保存一下即可。

2021-01-03 12:34 UTC, huanghyw commented
> 怎么考虑抢购IP封杀的处理
这个只能自己挂代理了

2021-01-03 12:34 UTC, closed without merging

2021-01-03 12:41 UTC, fisherpau commented
现在好像同时登陆6个号就会被服务器同时给踢掉

2021-01-03 12:44 UTC, fisherpau commented
把默认抢购数量可以放到config.ini里，seckill_num = 1，然后self.seckill_num = global_config.getRaw('config', 'seckill_num')

2021-01-04 02:45 UTC, flyhong666 commented
可以增加个设置抢购时长多少秒，到了设定时间后就不再抢购，停止。