增加：自动停止软件运行的功能
huanghyw/jd_seckill pull request #412
Opened 2021-01-03 12:39 UTC by wwwyeeting

额，老哥们，之前那个pull request被我误操作close了……非常抱歉

2021-01-03 13:23 UTC, kevin-garrnet-hh commented
> 
> 
> 额，老哥们，之前那个pull request被我误操作close了……非常抱歉

老哥，最后一步docker打印出二维码，手机扫描不上..docker配置文件里邮箱推送也推不上...普通配置文件里却可以配上..

2021-01-03 14:49 UTC, lucien0924 commented
你好 想请问一下 如果抢非茅台是不是会出现抢购链接获取失败？

2021-01-03 16:09 UTC, zhuyaozi commented
请教一下docker的开抢时间能自动更新吗？我刚才试了一下，compose.yml里的时间还是默认的01-01，容器建立以后，好像没有更新时间，认定时间为01-01了，然后开始疯狂的试图下单。。。

2021-01-04 01:22 UTC, caozanaaa commented
本地时间与jd服务器时间，有时候差1秒，有时候差0.2s，为什么啊

2021-01-04 02:05 UTC, KaiShu1 commented
INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】为啥一直返回这儿？

2021-01-04 02:07 UTC, git9980 commented
自动获取JdTdudfp发生异常，将从配置文件读取！

2021-01-04 02:07 UTC, EverthingHan999 commented
老哥，脚本启动后的二维码 app扫描不上是什么鬼  win10系统

2021-01-04 02:13 UTC, wwd460 commented
运行了  但是不见抢购,只是一直说  预约成功,与系统时间相差多少毫秒,开始执行之类的,是不是不会显示抢购失败,只有成功了才会显示订单之类的.

2021-01-04 02:15 UTC, wangxufire commented
> INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】为啥一直返回这儿？

+1

2021-01-04 02:22 UTC, chenyu276 commented
日志都是乱码，是怎么回事？

2021-01-04 02:32 UTC, alinjx commented
> > INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】为啥一直返回这儿？
> 
> +1

me too

2021-01-04 02:34 UTC, iOSGL commented
今天有抢到的老哥吗

2021-01-04 02:39 UTC, ZRT-1998 commented
之前更新的自动获取eid和fp，并不能使用
            await page.waitFor(".nickname")
            logger.info("page_title:【%s】, page_url【%s】" % (await page.title(), page.url))

            nick_name = await page.querySelectorEval(".nickname", "(element) => element.textContent")
            if not nick_name:
                # 如果未获取到用户昵称，说明可能登陆失败，放弃获取 _JdTdudfp
                return jd_tdudfp
到这里会获取不到用户昵称！
兄弟们点赞让大佬看见！

2021-01-04 02:40 UTC, iamlay commented
好像已经被京东风控检测到了，手机电脑一快抢的话，手机端需输入密码

2021-01-04 02:43 UTC, flyhong666 commented
看了下日志，我的号都是出现90016，但是有一次出现90008。

2021-01-04 02:45 UTC, chenyu276 commented
我的日子都是乱码，不知道咋回事




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "flyhong666"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 上午10:43
收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 
抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412)





 
看了下日志，我的号都是出现90016，但是有一次出现90008。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-04 02:46 UTC, 67snow commented
> 看了下日志，我的号都是出现90016，但是有一次出现90008。

小白信用多少分

2021-01-04 02:47 UTC, flyhong666 commented
> > 看了下日志，我的号都是出现90016，但是有一次出现90008。
> 
> 小白信用多少分

101.2

2021-01-04 02:48 UTC, flyhong666 commented
> 我的日子都是乱码，不知道咋回事
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flyhong666"<notifications@github.com&gt;; 发送时间: 2021年1月4日(星期一) 上午10:43 收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412) 看了下日志，我的号都是出现90016，但是有一次出现90008。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

编码的问题，用utf 8 就可以看到了。。

2021-01-04 02:50 UTC, chenyu276 commented
每次都是第一次运行的时候，日志是乱码， 清空日志后就正常了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "flyhong666"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 上午10:48
收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 
抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412)





  
我的日子都是乱码，不知道咋回事
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flyhong666"<notifications@github.com&gt;; 发送时间: 2021年1月4日(星期一) 上午10:43 收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412) 看了下日志，我的号都是出现90016，但是有一次出现90008。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
编码的问题，用utf 8 就可以看到了。。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-04 02:51 UTC, optolux commented
而且大家发没发现获取链接时间挺长的。基本上都得等个2秒才能获取到链接

2021-01-01 **10:00:01,568** - 14728-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=1e61340b5823525ac563906880fa7f86&from=pc
2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx8\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...

2021-01-04 **10:00:02,489** - 14088-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 **10:00:02,576** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=6b102a979a4f10a10ca7f9b3db4c781b&from=pc
2021-01-04 **10:00:02,577** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...

2021-01-04 02:52 UTC, chenyu276 commented
请问大佬，我同一台PC，切换账号，JdTdudfp的变量需要跟换吗，我看了下，切换账号后，这2个值是不变的





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "flyhong666"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 上午10:48
收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 
抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412)





  
我的日子都是乱码，不知道咋回事
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flyhong666"<notifications@github.com&gt;; 发送时间: 2021年1月4日(星期一) 上午10:43 收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412) 看了下日志，我的号都是出现90016，但是有一次出现90008。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
编码的问题，用utf 8 就可以看到了。。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-04 02:54 UTC, EverthingHan999 commented
> 而且大家发没发现获取链接时间挺长的。基本上都得等个2秒才能获取到链接
> 
> 2021-01-01 **10:00:01,568** - 14728-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=1e61340b5823525ac563906880fa7f86&from=pc
> 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx8\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...
> 
> 2021-01-04 **10:00:02,489** - 14088-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 **10:00:02,576** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=6b102a979a4f10a10ca7f9b3db4c781b&from=pc
> 2021-01-04 **10:00:02,577** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...

老哥 你们扫码登录都正常吗？我一扫就是各种商品信息。。。

2021-01-04 02:54 UTC, flyhong666 commented
> 请问大佬，我同一台PC，切换账号，JdTdudfp的变量需要跟换吗，我看了下，切换账号后，这2个值是不变的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flyhong666"<notifications@github.com&gt;; 发送时间: 2021年1月4日(星期一) 上午10:48 收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412) 我的日子都是乱码，不知道咋回事 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flyhong666"<notifications@github.com&gt;; 发送时间: 2021年1月4日(星期一) 上午10:43 收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412) 看了下日志，我的号都是出现90016，但是有一次出现90008。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 编码的问题，用utf 8 就可以看到了。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这个好像与账号没有关系的。是与系统和浏览器有关。

2021-01-04 02:56 UTC, optolux commented
> > 而且大家发没发现获取链接时间挺长的。基本上都得等个2秒才能获取到链接
> > 2021-01-01 **10:00:01,568** - 14728-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> > 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=1e61340b5823525ac563906880fa7f86&from=pc
> > 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx8\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...
> > 2021-01-04 **10:00:02,489** - 14088-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> > 2021-01-04 **10:00:02,576** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=6b102a979a4f10a10ca7f9b3db4c781b&from=pc
> > 2021-01-04 **10:00:02,577** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...
> 
> 老哥 你们扫码登录都正常吗？我一扫就是各种商品信息。。。

正常啊，我第一次用这个软件抢就成功了。之后帮朋友抢的时候都没成功，我就看了一下日志，发现获取链接的时间比较久的。

2021-01-04 02:57 UTC, flyhong666 commented
> 而且大家发没发现获取链接时间挺长的。基本上都得等个2秒才能获取到链接
> 
> 2021-01-01 **10:00:01,568** - 14728-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=1e61340b5823525ac563906880fa7f86&from=pc
> 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx8\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...
> 
> 2021-01-04 **10:00:02,489** - 14088-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 **10:00:02,576** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=6b102a979a4f10a10ca7f9b3db4c781b&from=pc
> 2021-01-04 **10:00:02,577** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...

的确是有一点。也没关系啦。第一次扫描登录后，这个地方的确有一点慢。

2021-01-04 02:57 UTC, KaiShu1 commented
> 而且大家发没发现获取链接时间挺长的。基本上都得等个2秒才能获取到链接
> 
> 2021-01-01 **10:00:01,568** - 14728-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=1e61340b5823525ac563906880fa7f86&from=pc
> 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx8\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...
> 
> 2021-01-04 **10:00:02,489** - 14088-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 **10:00:02,576** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=6b102a979a4f10a10ca7f9b3db4c781b&from=pc
> 2021-01-04 **10:00:02,577** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...

我也发现了，一到真正抢购获取的时候速度变慢很多。
![Uploading image.png…]()

2021-01-04 02:58 UTC, KaiShu1 commented
![image](https://user-images.githubusercontent.com/44948284/103497203-c0f29780-4e7b-11eb-8947-85309a8a8247.png)

2021-01-04 03:22 UTC, zhangpc310 commented
> 日志都是乱码，是怎么回事？

编辑器要修改格式为utf-8

2021-01-04 03:29 UTC, lc54516483 commented
为什么我大部分请求都是“无法获取生成订单的基本信息”， 正常么？

C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:577] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-04 10:02:43,717 - 9716-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:478] - INFO: 访问抢购订单结算页面...
2021-01-04 10:02:43,729 - 10616-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:521] - INFO: 生成提交抢购订单所需参数...
2021-01-04 10:02:43,729 - 10616-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:496] - INFO: 获取秒杀初始化信息...
2021-01-04 10:02:43,758 - 1312-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:577] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

2021-01-04 03:31 UTC, wo1348184465 commented
感谢, 第一次用就2瓶到手

2021-01-04 03:34 UTC, zkfopen commented
2021-01-04 11:29:21,678 - 78727-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 11:29:21,741 - 78729-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 11:29:21,753 - 78728-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 11:29:21,770 - 78725-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 11:29:21,920 - 78727-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 11:29:21,937 - 78726-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试

执行main.py文件之后，一直是"抢购链接获取失败，稍后自动重试"，持续时间30s以上，请问是正常的吗？

我理解是只有到每日10：00才能获取抢购链接成功是吗？

2021-01-04 03:35 UTC, flyhong666 commented
> 2021-01-04 11:29:21,678 - 78727-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 11:29:21,741 - 78729-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 11:29:21,753 - 78728-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 11:29:21,770 - 78725-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 11:29:21,920 - 78727-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 11:29:21,937 - 78726-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 
> 执行main.py文件之后，一直是"抢购链接获取失败，稍后自动重试"，持续时间30s以上，请问是正常的吗？
> 
> 我理解是只有到每日10：00才能获取抢购链接成功是吗？

这个应该是过了抢购时间，那个页面就没法再进去了。所有才导致出错吧。

2021-01-04 03:38 UTC, zkfopen commented
> > 2021-01-04 11:29:21,678 - 78727-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> > 2021-01-04 11:29:21,741 - 78729-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> > 2021-01-04 11:29:21,753 - 78728-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> > 2021-01-04 11:29:21,770 - 78725-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> > 2021-01-04 11:29:21,920 - 78727-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> > 2021-01-04 11:29:21,937 - 78726-MainThread - /Users/zhaikaifang/PycharmProjects/jd_seckill/jd_seckill/jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> > 执行main.py文件之后，一直是"抢购链接获取失败，稍后自动重试"，持续时间30s以上，请问是正常的吗？
> > 我理解是只有到每日10：00才能获取抢购链接成功是吗？
> 
> 这个应该是过了抢购时间，那个页面就没法再进去了。所有才导致出错吧。

是的，应该是这样。

2021-01-04 03:51 UTC, kevin-garrnet-hh commented
> 
> 
> 为什么我大部分请求都是“无法获取生成订单的基本信息”， 正常么？
> 
> C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:577] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> 2021-01-04 10:02:43,717 - 9716-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:478] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:02:43,729 - 10616-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:521] - INFO: 生成提交抢购订单所需参数...
> 2021-01-04 10:02:43,729 - 10616-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:496] - INFO: 获取秒杀初始化信息...
> 2021-01-04 10:02:43,758 - 1312-MainThread - C:\Users\nb\Desktop\jd_seckill-master\jd_seckill-master\jd_spider_requests.py[line:577] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-04 10:13:15,594 - 7560-MainThread - E:\firehox_download\jd_seckill-master\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:13:15,655 - 1912-MainThread - E:\firehox_download\jd_seckill-master\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90008, 'skuId': 0, 'success': False}
2021-01-04 10:13:15,655 - 1912-MainThread - E:\firehox_download\jd_seckill-master\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
我的也是这样。起码百分之60是无法获取生成订单的基本信息，老哥你是这样的吗

2021-01-04 03:57 UTC, zyzdnl123 commented
有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
是要配置docker才行吗？

2021-01-04 03:59 UTC, kevin-garrnet-hh commented
> 
> 
> 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> 是要配置docker才行吗？

docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。

2021-01-04 04:00 UTC, zyzdnl123 commented
> > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > 是要配置docker才行吗？
> 
> docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。

谢谢大佬

2021-01-04 04:01 UTC, kevin-garrnet-hh commented
> 
> 
> > > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > > 是要配置docker才行吗？
> > 
> > 
> > docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。
> 
> 谢谢大佬

你今天测试成功了吗，我想看看你的日志文件.. 是不是有一半多都是无法生成订单啊。我不是大佬哈哈哈

2021-01-04 04:02 UTC, zyzdnl123 commented
> > > > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > > > 是要配置docker才行吗？
> > > 
> > > 
> > > docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。
> > 
> > 
> > 谢谢大佬
> 
> 你今天测试成功了吗，我想看看你的日志文件.. 是不是有一半多都是无法生成订单啊。我不是大佬哈哈哈

我跑了3天了，都没有抢到，你可以告诉我怎么去看日志，我是小白，不怎么会python

2021-01-04 04:03 UTC, kevin-garrnet-hh commented
> 
> 
> > > > > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > > > > 是要配置docker才行吗？
> > > > 
> > > > 
> > > > docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。
> > > 
> > > 
> > > 谢谢大佬
> > 
> > 
> > 你今天测试成功了吗，我想看看你的日志文件.. 是不是有一半多都是无法生成订单啊。我不是大佬哈哈哈
> 
> 我跑了3天了，都没有抢到，你可以告诉我怎么去看日志，我是小白，不怎么会python

项目文件里面有个jd_seckill.log，你打开看就是了

2021-01-04 04:08 UTC, Derek970620 commented
日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！

2021-01-04 04:08 UTC, zyzdnl123 commented
> > > > > > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > > > > > 是要配置docker才行吗？
> > > > > 
> > > > > 
> > > > > docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。
> > > > 
> > > > 
> > > > 谢谢大佬
> > > 
> > > 
> > > 你今天测试成功了吗，我想看看你的日志文件.. 是不是有一半多都是无法生成订单啊。我不是大佬哈哈哈
> > 
> > 
> > 我跑了3天了，都没有抢到，你可以告诉我怎么去看日志，我是小白，不怎么会python
> 
> 项目文件里面有个jd_seckill.log，你打开看就是了

2021-01-04 10:00:05,329 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:00:05,355 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
2021-01-04 10:00:05,358 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
2021-01-04 10:00:05,589 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90008, 'skuId': 0, 'success': False}
2021-01-04 10:00:05,591 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:00:05,628 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
2021-01-04 10:00:05,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
2021-01-04 10:00:05,719 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
2021-01-04 10:00:05,720 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
2021-01-04 10:00:05,842 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-04 10:00:05,844 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:00:05,908 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
2021-01-04 10:00:05,909 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
2021-01-04 10:00:06,116 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
2021-01-04 10:00:06,120 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
2021-01-04 10:00:06,140 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
2021-01-04 10:00:06,141 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
2021-01-04 10:00:06,352 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-04 10:00:06,355 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:00:06,495 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-04 10:00:06,498 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:00:06,627 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
2021-01-04 10:00:06,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
2021-01-04 10:00:06,678 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-04 10:00:06,680 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
2021-01-04 10:00:06,780 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
2021-01-04 10:00:06,782 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
2021-01-04 10:00:06,835 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-04 10:00:06,837 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...

2021-01-04 04:09 UTC, kevin-garrnet-hh commented
> 
> 
> > > > > > > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > > > > > > 是要配置docker才行吗？
> > > > > > 
> > > > > > 
> > > > > > docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。
> > > > > 
> > > > > 
> > > > > 谢谢大佬
> > > > 
> > > > 
> > > > 你今天测试成功了吗，我想看看你的日志文件.. 是不是有一半多都是无法生成订单啊。我不是大佬哈哈哈
> > > 
> > > 
> > > 我跑了3天了，都没有抢到，你可以告诉我怎么去看日志，我是小白，不怎么会python
> > 
> > 
> > 项目文件里面有个jd_seckill.log，你打开看就是了
> 
> 2021-01-04 10:00:05,329 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:00:05,355 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
> 2021-01-04 10:00:05,358 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
> 2021-01-04 10:00:05,589 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90008, 'skuId': 0, 'success': False}
> 2021-01-04 10:00:05,591 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:00:05,628 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> 2021-01-04 10:00:05,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> 2021-01-04 10:00:05,719 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> 2021-01-04 10:00:05,720 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> 2021-01-04 10:00:05,842 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> 2021-01-04 10:00:05,844 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:00:05,908 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> 2021-01-04 10:00:05,909 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> 2021-01-04 10:00:06,116 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
> 2021-01-04 10:00:06,120 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
> 2021-01-04 10:00:06,140 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> 2021-01-04 10:00:06,141 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> 2021-01-04 10:00:06,352 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> 2021-01-04 10:00:06,355 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:00:06,495 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> 2021-01-04 10:00:06,498 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> 2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:00:06,627 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> 2021-01-04 10:00:06,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> 2021-01-04 10:00:06,678 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> 2021-01-04 10:00:06,680 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 2021-01-04 10:00:06,780 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> 2021-01-04 10:00:06,782 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> 2021-01-04 10:00:06,835 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> 2021-01-04 10:00:06,837 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...

额..一样的。

2021-01-04 04:10 UTC, zyzdnl123 commented
> > > > > > > > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > > > > > > > 是要配置docker才行吗？
> > > > > > > 
> > > > > > > 
> > > > > > > docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。
> > > > > > 
> > > > > > 
> > > > > > 谢谢大佬
> > > > > 
> > > > > 
> > > > > 你今天测试成功了吗，我想看看你的日志文件.. 是不是有一半多都是无法生成订单啊。我不是大佬哈哈哈
> > > > 
> > > > 
> > > > 我跑了3天了，都没有抢到，你可以告诉我怎么去看日志，我是小白，不怎么会python
> > > 
> > > 
> > > 项目文件里面有个jd_seckill.log，你打开看就是了
> > 
> > 
> > 2021-01-04 10:00:05,329 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 2021-01-04 10:00:05,355 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
> > 2021-01-04 10:00:05,358 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
> > 2021-01-04 10:00:05,589 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90008, 'skuId': 0, 'success': False}
> > 2021-01-04 10:00:05,591 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 2021-01-04 10:00:05,628 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > 2021-01-04 10:00:05,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > 2021-01-04 10:00:05,719 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > 2021-01-04 10:00:05,720 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > 2021-01-04 10:00:05,842 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > 2021-01-04 10:00:05,844 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 2021-01-04 10:00:05,908 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > 2021-01-04 10:00:05,909 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > 2021-01-04 10:00:06,116 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
> > 2021-01-04 10:00:06,120 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
> > 2021-01-04 10:00:06,140 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > 2021-01-04 10:00:06,141 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > 2021-01-04 10:00:06,352 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > 2021-01-04 10:00:06,355 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 2021-01-04 10:00:06,495 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > 2021-01-04 10:00:06,498 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > 2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 2021-01-04 10:00:06,627 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > 2021-01-04 10:00:06,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > 2021-01-04 10:00:06,678 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > 2021-01-04 10:00:06,680 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 2021-01-04 10:00:06,780 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > 2021-01-04 10:00:06,782 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > 2021-01-04 10:00:06,835 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > 2021-01-04 10:00:06,837 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> 
> 额..一样的。

9008和90016都出现了

2021-01-04 04:10 UTC, kevin-garrnet-hh commented
> 
> 
> > > > > > > > > 有没有大佬知道，多的一个docker运行是什么意思？我发现不需要这个docker也可以运行的啊？
> > > > > > > > > 是要配置docker才行吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > docker好像是自动获取配置的，我两种方式都试了，2个都可以抢。
> > > > > > > 
> > > > > > > 
> > > > > > > 谢谢大佬
> > > > > > 
> > > > > > 
> > > > > > 你今天测试成功了吗，我想看看你的日志文件.. 是不是有一半多都是无法生成订单啊。我不是大佬哈哈哈
> > > > > 
> > > > > 
> > > > > 我跑了3天了，都没有抢到，你可以告诉我怎么去看日志，我是小白，不怎么会python
> > > > 
> > > > 
> > > > 项目文件里面有个jd_seckill.log，你打开看就是了
> > > 
> > > 
> > > 2021-01-04 10:00:05,329 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > > 2021-01-04 10:00:05,355 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
> > > 2021-01-04 10:00:05,358 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
> > > 2021-01-04 10:00:05,589 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90008, 'skuId': 0, 'success': False}
> > > 2021-01-04 10:00:05,591 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > > 2021-01-04 10:00:05,628 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > > 2021-01-04 10:00:05,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > > 2021-01-04 10:00:05,719 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > > 2021-01-04 10:00:05,720 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > > 2021-01-04 10:00:05,842 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > > 2021-01-04 10:00:05,844 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > > 2021-01-04 10:00:05,908 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > > 2021-01-04 10:00:05,909 - 8296-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > > 2021-01-04 10:00:06,116 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:658] - INFO: order_date：{}
> > > 2021-01-04 10:00:06,120 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:675] - INFO: 提交抢购订单...
> > > 2021-01-04 10:00:06,140 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > > 2021-01-04 10:00:06,141 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > > 2021-01-04 10:00:06,352 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > > 2021-01-04 10:00:06,355 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > > 2021-01-04 10:00:06,495 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > > 2021-01-04 10:00:06,498 - 11156-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > > 2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:711] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > 2021-01-04 10:00:06,521 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > > 2021-01-04 10:00:06,627 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > > 2021-01-04 10:00:06,630 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > > 2021-01-04 10:00:06,678 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > > 2021-01-04 10:00:06,680 - 10576-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > > 2021-01-04 10:00:06,780 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:616] - INFO: 生成提交抢购订单所需参数...
> > > 2021-01-04 10:00:06,782 - 10944-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:591] - INFO: 获取秒杀初始化信息...
> > > 2021-01-04 10:00:06,835 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:672] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> > > 2021-01-04 10:00:06,837 - 11144-MainThread - F:\jd\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:573] - INFO: 访问抢购订单结算页面...
> > 
> > 
> > 额..一样的。
> 
> 9008和90016都出现了

是的，慢慢抢吧。应该没问题

2021-01-04 04:12 UTC, kevin-garrnet-hh commented
> 
> 
> 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到

你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧

2021-01-04 04:15 UTC, flyhong666 commented
用来抢华为的美腿全是 90008 ，吐血啊。。。

2021-01-04 04:15 UTC, lin-github5812 commented
7] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=56eb29b125c64a7516781c025b754e4f&from=pc
 10:00:00,944 - 21732-MainThread -\jd_seckill-master\jd_spider_requests.py[line:469] - INFO: 访问商品的抢购连接...
10:00:01,026 - 21732-MainThread -jd_seckill-master\jd_spider_requests.py[line:483] - INFO: 访问抢购订单结算页面...
 10:00:01,031 - 13712-MainThread -jd_seckill-master\jd_spider_requests.py[line:457] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=56eb29b125c64a7516781c025b754e4f&from=pc
 10:00:01,031 - 13712-MainThread - jd_seckill-master\jd_spider_requests.py[line:469] - INFO: 访问商品的抢购连接...
 10:00:01,055 - 6208-MainThread -jd_seckill-master\jd_spider_requests.py[line:457] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=56eb29b125c64a7516781c025b754e4f&from=pc
 10:00:01,056 - 6208-MainThread -d_seckill-master\jd_spider_requests.py[line:469] - INFO: 访问商品的抢购连接...
 10:00:01,065 - 15432-MainThread - jd_seckill-master\jd_spider_requests.py[line:457] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=56eb29b125c64a7516781c025b754e4f&from=pc
 10:00:01,065 - 15432-MainThread - jd_seckill-master\jd_spider_requests.py[line:469] - INFO: 访问商品的抢购连接...
 10:00:01,186 - 15432-MainThread - jd_seckill-master\jd_spider_requests.py[line:483] - INFO: 访问抢购订单结算页面...
10:00:01,352 - 13812-MainThread -jd_seckill-master\jd_spider_requests.py[line:457] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=56eb29b125c64a7516781c025b754e4f&from=pc
 10:00:01,352 - 13812-MainThread - d_seckill-master\jd_spider_requests.py[line:469] - INFO: 访问商品的抢购连接...
 10:00:01,358 - 13712-MainThread -d_seckill-master\jd_spider_requests.py[line:483] - INFO: 访问抢购订单结算页面...

------获得链接，访问结算页面，，再就又去重复访问链接了，不知道是什么问题，，各位有遇到过吗

2021-01-04 04:16 UTC, Derek970620 commented
> 
> 
> > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> 
> 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧

我用的不是docker

2021-01-04 04:17 UTC, kevin-garrnet-hh commented
> 
> 
> > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > 
> > 
> > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> 
> 我用的不是docker

博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行

2021-01-04 04:20 UTC, Derek970620 commented
> 
> 
> > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > 
> > > 
> > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > 
> > 
> > 我用的不是docker
> 
> 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行

昨天我在家还是可以获取到的，今天就获取不到了

2021-01-04 04:21 UTC, flyhong666 commented
> > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > 
> > > > 
> > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > 
> > > 
> > > 我用的不是docker
> > 
> > 
> > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> 
> 昨天我在家还是可以获取到的，今天就获取不到了

我的都没法自动获取到，都是自己手动弄eid和fp上去的。

2021-01-04 04:21 UTC, kevin-garrnet-hh commented
> 
> 
> > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > 
> > > > 
> > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > 
> > > 
> > > 我用的不是docker
> > 
> > 
> > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> 
> 昨天我在家还是可以获取到的，今天就获取不到了

我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗

2021-01-04 05:20 UTC, Derek970620 commented
> 
> 
> > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > 
> > > > > 
> > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > 
> > > > 
> > > > 我用的不是docker
> > > 
> > > 
> > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > 
> > 
> > 昨天我在家还是可以获取到的，今天就获取不到了
> 
> 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗

是的 直接运行main的

2021-01-04 05:46 UTC, fanyangyang188 commented
有抢到的吗今天

2021-01-04 06:15 UTC, 67snow commented
> > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > 
> > > > > > 
> > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > 
> > > > > 
> > > > > 我用的不是docker
> > > > 
> > > > 
> > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > 
> > > 
> > > 昨天我在家还是可以获取到的，今天就获取不到了
> > 
> > 
> > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> 
> 是的 直接运行main的

解决了吗？我也遇到这个问题了

2021-01-04 06:29 UTC, Derek970620 commented
> 
> 
> > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > 
> > > > > > > 
> > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > 
> > > > > > 
> > > > > > 我用的不是docker
> > > > > 
> > > > > 
> > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > 
> > > > 
> > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > 
> > > 
> > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > 
> > 
> > 是的 直接运行main的
> 
> 解决了吗？我也遇到这个问题了

还没解决

2021-01-04 06:31 UTC, unisong commented
> > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > 
> > > > > > > 
> > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > 
> > > > > > 
> > > > > > 我用的不是docker
> > > > > 
> > > > > 
> > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > 
> > > > 
> > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > 
> > > 
> > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > 
> > 
> > 是的 直接运行main的
> 
> 解决了吗？我也遇到这个问题了

我也。。。昨天在家里还是可以的，今天到公司后也获取不到了

2021-01-04 06:31 UTC, chenyu276 commented
这两个值，自己获取一下手动填写比较靠谱




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Derek970620"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 下午2:29
收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 
抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412)





         
日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
  
你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
  
我用的不是docker
  
博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
  
昨天我在家还是可以获取到的，今天就获取不到了
  
我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
  
是的 直接运行main的
  
解决了吗？我也遇到这个问题了
  
还没解决
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-04 06:45 UTC, unisong commented
请选择:1
[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:63604/devtools/browser/d632a0fe-d586-463e-81b7-adfc58907f83
2021-01-04 14:42:30,460 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:309] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2021-01-04 14:42:40,663 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:324] - INFO: page_title：【家用电器】, page_url：【https://jiadian.jd.com/】
2021-01-04 14:43:10,668 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:352] - INFO: 自 动获取JdTdudfp发生异常，将从配置文件读取！
2021-01-04 14:43:10,747 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:459] - INFO: 商 品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2021-01-04 14:43:10,790 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定 时间:2021-01-05 10:00:00，检测本地时间与京东服务器时间误差为【430】毫秒
为啥我这儿会跳转进去一个京东家电的地址？

2021-01-04 06:46 UTC, kevin-garrnet-hh commented
> 
> 
> 请选择:1
> [I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:63604/devtools/browser/d632a0fe-d586-463e-81b7-adfc58907f83
> 2021-01-04 14:42:30,460 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:309] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【[https://www.jd.com/】](https://www.jd.com/%E3%80%91)
> 2021-01-04 14:42:40,663 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:324] - INFO: page_title：【家用电器】, page_url：【[https://jiadian.jd.com/】](https://jiadian.jd.com/%E3%80%91)
> 2021-01-04 14:43:10,668 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:352] - INFO: 自 动获取JdTdudfp发生异常，将从配置文件读取！
> 2021-01-04 14:43:10,747 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:459] - INFO: 商 品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 14:43:10,790 - 12304-MainThread - C:\jd_seckill-master\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定 时间:2021-01-05 10:00:00，检测本地时间与京东服务器时间误差为【430】毫秒
> 为啥我这儿会跳转进去一个京东家电的地址？

自动获取配置值..

2021-01-04 07:52 UTC, kevin-garrnet-hh commented
> 
> 
> > > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > > 
> > > > > > > 
> > > > > > > 我用的不是docker
> > > > > > 
> > > > > > 
> > > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > > 
> > > > > 
> > > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > > 
> > > > 
> > > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > > 
> > > 
> > > 是的 直接运行main的
> > 
> > 
> > 解决了吗？我也遇到这个问题了
> 
> 还没解决

手动添加吧，应该没什么影响

2021-01-04 07:59 UTC, 67snow commented
> > > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > > 
> > > > > > > 
> > > > > > > 我用的不是docker
> > > > > > 
> > > > > > 
> > > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > > 
> > > > > 
> > > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > > 
> > > > 
> > > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > > 
> > > 
> > > 是的 直接运行main的
> > 
> > 
> > 解决了吗？我也遇到这个问题了
> 
> 我也。。。昨天在家里还是可以的，今天到公司后也获取不到了

又搞了搞，与配置的时间有关系。时间不能小于当前的时间。（非专业python开发）

2021-01-04 08:03 UTC, kevin-garrnet-hh commented
> 
> 
> > > > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我用的不是docker
> > > > > > > 
> > > > > > > 
> > > > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > > > 
> > > > > > 
> > > > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > > > 
> > > > > 
> > > > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > > > 
> > > > 
> > > > 是的 直接运行main的
> > > 
> > > 
> > > 解决了吗？我也遇到这个问题了
> > 
> > 
> > 我也。。。昨天在家里还是可以的，今天到公司后也获取不到了
> 
> 又搞了搞，与配置的时间有关系。时间不能小于当前的时间。（非专业python开发）

时间不能小于当前时间？buy_time吗

2021-01-04 08:23 UTC, Derek970620 commented
> 
> 
> > > > > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我用的不是docker
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > > > > 
> > > > > > > 
> > > > > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > > > > 
> > > > > > 
> > > > > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > > > > 
> > > > > 
> > > > > 是的 直接运行main的
> > > > 
> > > > 
> > > > 解决了吗？我也遇到这个问题了
> > > 
> > > 
> > > 我也。。。昨天在家里还是可以的，今天到公司后也获取不到了
> > 
> > 
> > 又搞了搞，与配置的时间有关系。时间不能小于当前的时间。（非专业python开发）
> 
> 时间不能小于当前时间？buy_time吗

我时间就是没小于当前时间，也是不行

2021-01-04 08:26 UTC, 67snow commented
> > > > > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我用的不是docker
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > > > > 
> > > > > > > 
> > > > > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > > > > 
> > > > > > 
> > > > > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > > > > 
> > > > > 
> > > > > 是的 直接运行main的
> > > > 
> > > > 
> > > > 解决了吗？我也遇到这个问题了
> > > 
> > > 
> > > 我也。。。昨天在家里还是可以的，今天到公司后也获取不到了
> > 
> > 
> > 又搞了搞，与配置的时间有关系。时间不能小于当前的时间。（非专业python开发）
> 
> 时间不能小于当前时间？buy_time吗

2021-01-04 16:25:21,135 - 10228-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:352] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2021-01-04 16:25:21,744 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
2021-01-04 16:25:21,757 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
2021-01-04 16:25:21,776 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
2021-01-04 16:25:22,152 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2021-01-04 16:25:22,152 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
2021-01-04 16:25:22,160 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2021-01-04 16:25:22,161 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
2021-01-04 16:25:22,246 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2021-01-04 16:25:22,246 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
2021-01-04 16:25:22,264 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:67snow
2021-01-04 16:25:22,431 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:67snow
2021-01-04 16:25:22,629 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2021-01-04 16:25:22,629 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
2021-01-04 16:25:22,871 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2021-01-04 16:25:22,871 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
2021-01-04 16:25:59,419 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
2021-01-04 16:25:59,595 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 16:25:59,677 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
2021-01-04 16:25:59,735 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
2021-01-04 16:25:59,738 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
2021-01-04 16:25:59,797 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
2021-01-04 16:25:59,844 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 16:25:59,899 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 16:25:59,899 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
2021-01-04 16:25:59,946 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试

2021-01-04 08:28 UTC, Xiejing1996 commented
> > > 而且大家发没发现获取链接时间挺长的。基本上都得等个2秒才能获取到链接
> > > 2021-01-01 **10:00:01,568** - 14728-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> > > 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=1e61340b5823525ac563906880fa7f86&from=pc
> > > 2021-01-01 **10:00:01,638** - 11284-MainThread - C:\xxx8\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...
> > > 2021-01-04 **10:00:02,489** - 14088-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:466] - INFO: 抢购链接获取失败，稍后自动重试
> > > 2021-01-04 **10:00:02,576** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:463] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=6b102a979a4f10a10ca7f9b3db4c781b&from=pc
> > > 2021-01-04 **10:00:02,577** - 14076-MainThread - C:\xxx\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:475] - INFO: 访问商品的抢购连接...
> > 
> > 
> > 老哥 你们扫码登录都正常吗？我一扫就是各种商品信息。。。
> 
> 正常啊，我第一次用这个软件抢就成功了。之后帮朋友抢的时候都没成功，我就看了一下日志，发现获取链接的时间比较久的。

老哥，我想问下我用pycharm运行main.py,需要把浏览器打开吗，如果用不到浏览器的话填写浏览器用户代理是干嘛用啊

2021-01-04 08:28 UTC, 67snow commented
> > > > > > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我用的不是docker
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > > > > > 
> > > > > > > 
> > > > > > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > > > > > 
> > > > > > 
> > > > > > 是的 直接运行main的
> > > > > 
> > > > > 
> > > > > 解决了吗？我也遇到这个问题了
> > > > 
> > > > 
> > > > 我也。。。昨天在家里还是可以的，今天到公司后也获取不到了
> > > 
> > > 
> > > 又搞了搞，与配置的时间有关系。时间不能小于当前的时间。（非专业python开发）
> > 
> > 
> > 时间不能小于当前时间？buy_time吗
> 
> 2021-01-04 16:25:21,135 - 10228-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:352] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
> 2021-01-04 16:25:21,744 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
> 2021-01-04 16:25:21,757 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
> 2021-01-04 16:25:21,776 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
> 2021-01-04 16:25:22,152 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,152 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,160 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,161 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,246 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,246 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,264 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:67snow
> 2021-01-04 16:25:22,431 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:67snow
> 2021-01-04 16:25:22,629 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,629 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,871 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,871 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:59,419 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,595 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,677 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,735 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,738 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,797 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,844 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,899 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,899 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,946 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试

猜测：下一场抢购时间未到（明天10:00），所以抢购链接获取失败？上面是我设置的大于当前时间的。

2021-01-04 08:29 UTC, flyhong666 commented
> > > > > > > > > > > > 日志出现:自动获取JdTdudfp发生异常，将从配置文件读取！有没有大佬遇到
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 你是用docker的吗，用docker的话多重新打开镜像几次。没用dokcer就直接写在配置文件里面吧
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我用的不是docker
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 博主用docker好像就是自动获取配置的。你没用的话就自己写嘛，能抢就行
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 昨天我在家还是可以获取到的，今天就获取不到了
> > > > > > > 
> > > > > > > 
> > > > > > > 我用的docker可以获取。不用docker也是获取失败..你是直接运行的main吗
> > > > > > 
> > > > > > 
> > > > > > 是的 直接运行main的
> > > > > 
> > > > > 
> > > > > 解决了吗？我也遇到这个问题了
> > > > 
> > > > 
> > > > 我也。。。昨天在家里还是可以的，今天到公司后也获取不到了
> > > 
> > > 
> > > 又搞了搞，与配置的时间有关系。时间不能小于当前的时间。（非专业python开发）
> > 
> > 
> > 时间不能小于当前时间？buy_time吗
> 
> 2021-01-04 16:25:21,135 - 10228-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:352] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
> 2021-01-04 16:25:21,744 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
> 2021-01-04 16:25:21,757 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
> 2021-01-04 16:25:21,776 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:（我的nicknam）
> 2021-01-04 16:25:22,152 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,152 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,160 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,161 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,246 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,246 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,264 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:67snow
> 2021-01-04 16:25:22,431 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:555] - INFO: 用户:67snow
> 2021-01-04 16:25:22,629 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,629 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:22,871 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:556] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2021-01-04 16:25:22,871 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:48] - INFO: 正在等待到达设定时间:2021-01-04 16:25:59.500000，检测本地时间与京东服务器时间误差为【-196】毫秒
> 2021-01-04 16:25:59,419 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,595 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,677 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,735 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,738 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,797 - 3076-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\timer.py[line:53] - INFO: 时间到达，开始执行……
> 2021-01-04 16:25:59,844 - 14492-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,899 - 18064-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,899 - 13684-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试
> 2021-01-04 16:25:59,946 - 12340-MainThread - E:\APP\phpStudy\PHPTutorial\WWW\jd_seckill\jd_seckill\jd_spider_requests.py[line:550] - INFO: 抢购链接获取失败，稍后自动重试

非抢购时间，现在那个页面没法访问的，别试了吧。现在都还是处于预约状态。

2021-01-04 08:46 UTC, hrbboyzonemx commented
请问如何手动停止抢购？小白一名，谢谢

2021-01-04 08:47 UTC, flyhong666 commented
> 请问如何手动停止抢购？小白一名，谢谢

按键盘上的 ctrl+C

2021-01-04 09:01 UTC, wanghuohuo0716 commented
telegram群：https://t.me/joinchat/HSd9wdUd2ruDvdvo

2021-01-04 09:57 UTC, wanghlstar commented
cookies ~~ 能用手机验证码的，保留30天有效就好了~~不用每天扫码~~~ 就可以加个定时任务了~~~ 
today=`date '+%Y-%m-%d 09:59:59.500'`
last_day=`grep "09:59:59" config.ini | awk -F '= ' '{print $2}'` 
sed -i '' "s/$last_day/$today/g" config.ini ###mac的  -i 需要加个''

2021-01-04 10:01 UTC, wanghuohuo0716 commented
> cookies ~~ 能用手机验证码的，保留30天有效就好了~~不用每天扫码~~~ 就可以加个定时任务了~~~
> today=`date '+%Y-%m-%d 09:59:59.500'`
> last_day=`grep "09:59:59" config.ini | awk -F '= ' '{print $2}'`
> sed -i '' "s/$last_day/$today/g" config.ini ###mac的 -i 需要加个''

麻烦问下这个持续30天的cookies是网页版选择密码登录吗？网页版没有验证码登录

2021-01-04 10:10 UTC, huanghyw requested changes

2021-01-04 10:10 UTC, huanghyw commented on config.ini
> +continue_time = 5
同学，Dockerfile和docker.env这两个文件也同步修改一下，不然docker环境里面读不到这个值

2021-01-04 10:19 UTC, YYzoneYY commented
No container found for jd-seckill_1是什么意思

2021-01-04 10:21 UTC, huanghyw commented
> 之前更新的自动获取eid和fp，并不能使用
> await page.waitFor(".nickname")
> logger.info("page_title:【%s】, page_url【%s】" % (await page.title(), page.url))
> 
> ```
>         nick_name = await page.querySelectorEval(".nickname", "(element) => element.textContent")
>         if not nick_name:
>             # 如果未获取到用户昵称，说明可能登陆失败，放弃获取 _JdTdudfp
>             return jd_tdudfp
> ```
> 
> 到这里会获取不到用户昵称！
> 兄弟们点赞让大佬看见！

刚才试了下，我这复现不了这个问题
哪个同学有条件的走一下断点，看看什么原因

初步估计是页面加载太慢导致wait超时，先手动多试几次，后续把自动重试加上

2021-01-04 10:23 UTC, flyhong666 commented on config.ini
> +continue_time = 5
不需要搞5分钟这么长时间吧。号好的话，1、2秒就搞掂，号不好，抢再久也是白搭。

2021-01-04 10:23 UTC, huanghyw commented
非docker环境无法获取`_JdTdudfp`的同学更新代码之后重新执行一次`pip install -r requirements.txt`，因为添加了新的三方包

2021-01-04 10:27 UTC, flyhong666 commented
> 非docker环境无法获取`_JdTdudfp`的同学更新代码之后重新执行一次`pip install -r requirements.txt`，因为添加了新的三方包

我Windows 10 ，安装的是python 3.9.1 ，这句话也执行过了。还是没法自动获取。

2021-01-04 10:42 UTC, Derek970620 commented
> 
> 
> 非docker环境无法获取`_JdTdudfp`的同学更新代码之后重新执行一次`pip install -r requirements.txt`，因为添加了新的三方包

我也执行了，昨天还可以，我打断点看应该是goto那个方法出现问题了

2021-01-04 11:37 UTC, TeamKevin commented
异常:自动获取JdTdudfp发生异常，将从配置文件读取！
求大佬指教如何获取eid和fd

2021-01-04 13:11 UTC, samGly commented on config.ini
> +continue_time = 5
> 不需要搞5分钟这么长时间吧。号好的话，1、2秒就搞掂，号不好，抢再久也是白搭。

大哥能指导我一些问题吗

2021-01-04 14:01 UTC, wwwyeeting commented on config.ini
> +continue_time = 5
第一次用pull request，不太会哈，老哥们看下修改成这样能合入了没？
@huanghyw docker的两份文件我也加上了，你看一下，docker我没使用过所以你不说的话我真不知道。
@flyhong666 这部分可以让用户自己改的。5分钟的话也不长，而且程序会自动停止所以不需要人为干预的，软件能更傻瓜一些。

2021-01-04 14:11 UTC, flyhong666 commented on config.ini
> +continue_time = 5
你这个可以设置为小数不？如0.5 分钟

2021-01-04 14:14 UTC, flyhong666 commented on config.ini
> +continue_time = 5
> > 不需要搞5分钟这么长时间吧。号好的话，1、2秒就搞掂，号不好，抢再久也是白搭。
> 
> 大哥能指导我一些问题吗

不敢当，有啥说说看呗。

2021-01-04 14:19 UTC, samGly commented on config.ini
> +continue_time = 5
我打包在win环境下运行了，不知道抢的时候怎么操作，今天试了一下，用功能1的话，到时间之后日志显示已预约成功，程序退出了，2功能的话，是不是要到时间人工使用2功能啊

2021-01-04 14:41 UTC, flyhong666 commented on config.ini
> +continue_time = 5
你设置好时间，然后启动选择2 就是啦。到了时间就会自动进行的啦。不能关闭当前程序。

2021-01-04 15:04 UTC, flyhong666 commented
> 非docker环境无法获取`_JdTdudfp`的同学更新代码之后重新执行一次`pip install -r requirements.txt`，因为添加了新的三方包

大佬，合并一下那个可以设置时间自动停止的呗。

2021-01-04 16:00 UTC, ZRT-1998 commented
> > 之前更新的自动获取eid和fp，并不能使用
> > await page.waitFor(".nickname")
> > logger.info("page_title:【%s】, page_url【%s】" % (await page.title(), page.url))
> > ```
> >         nick_name = await page.querySelectorEval(".nickname", "(element) => element.textContent")
> >         if not nick_name:
> >             # 如果未获取到用户昵称，说明可能登陆失败，放弃获取 _JdTdudfp
> >             return jd_tdudfp
> > ```
> > 
> > 
> > 到这里会获取不到用户昵称！
> > 兄弟们点赞让大佬看见！
> 
> 刚才试了下，我这复现不了这个问题
> 哪个同学有条件的走一下断点，看看什么原因
> 
> 初步估计是页面加载太慢导致wait超时，先手动多试几次，后续把自动重试加上

818957644

> > 之前更新的自动获取eid和fp，并不能使用
> > await page.waitFor(".nickname")
> > logger.info("page_title:【%s】, page_url【%s】" % (await page.title(), page.url))
> > ```
> >         nick_name = await page.querySelectorEval(".nickname", "(element) => element.textContent")
> >         if not nick_name:
> >             # 如果未获取到用户昵称，说明可能登陆失败，放弃获取 _JdTdudfp
> >             return jd_tdudfp
> > ```
> > 
> > 
> > 到这里会获取不到用户昵称！
> > 兄弟们点赞让大佬看见！
> 
> 刚才试了下，我这复现不了这个问题
> 哪个同学有条件的走一下断点，看看什么原因
> 
> 初步估计是页面加载太慢导致wait超时，先手动多试几次，后续把自动重试加上

![746fc2e98c8c9b31](https://user-images.githubusercontent.com/34241963/103553820-f2ee1300-4ee8-11eb-934b-cc5c37de4dc7.jpg)
断点此处停止运行

2021-01-04 16:02 UTC, ZRT-1998 commented
> > 之前更新的自动获取eid和fp，并不能使用
> > await page.waitFor(".nickname")
> > logger.info("page_title:【%s】, page_url【%s】" % (await page.title(), page.url))
> > ```
> >         nick_name = await page.querySelectorEval(".nickname", "(element) => element.textContent")
> >         if not nick_name:
> >             # 如果未获取到用户昵称，说明可能登陆失败，放弃获取 _JdTdudfp
> >             return jd_tdudfp
> > ```
> > 
> > 
> > 到这里会获取不到用户昵称！
> > 兄弟们点赞让大佬看见！
> 
> 刚才试了下，我这复现不了这个问题
> 哪个同学有条件的走一下断点，看看什么原因
> 
> 初步估计是页面加载太慢导致wait超时，先手动多试几次，后续把自动重试加上

![746fc2e98c8c9b31](https://user-images.githubusercontent.com/34241963/103553990-33e62780-4ee9-11eb-8d50-92c4a5b08eee.jpg)
断点到此处停止运行

2021-01-04 16:19 UTC, houxianyj commented
> 本地时间与jd服务器时间，有时候差1秒，有时候差0.2s，为什么啊

因为请求jd时间接口时间长了。网络不是每次都很快

2021-01-04 16:40 UTC, thethirdfive commented
> > > 之前更新的自动获取eid和fp，并不能使用
> > > await page.waitFor(".nickname")
> > > logger.info("page_title:【%s】, page_url【%s】" % (await page.title(), page.url))
> > > ```
> > >         nick_name = await page.querySelectorEval(".nickname", "(element) => element.textContent")
> > >         if not nick_name:
> > >             # 如果未获取到用户昵称，说明可能登陆失败，放弃获取 _JdTdudfp
> > >             return jd_tdudfp
> > > ```
> > > 
> > > 
> > > 到这里会获取不到用户昵称！
> > > 兄弟们点赞让大佬看见！
> > 
> > 
> > 刚才试了下，我这复现不了这个问题
> > 哪个同学有条件的走一下断点，看看什么原因
> > 初步估计是页面加载太慢导致wait超时，先手动多试几次，后续把自动重试加上
> 
> ![746fc2e98c8c9b31](https://user-images.githubusercontent.com/34241963/103553990-33e62780-4ee9-11eb-8d50-92c4a5b08eee.jpg)
> 断点到此处停止运行
> 异常:自动获取JdTdudfp发生异常，将从配置文件读取！

这个问题我提了pr,可以看下 [https://github.com/huanghyw/jd_seckill/pull/423](url)

2021-01-05 00:32 UTC, wwwyeeting commented on config.ini
> +continue_time = 5
`buy_time = datetime.strptime('2021-01-01 10:00:00.000', "%Y-%m-%d %H:%M:%S.%f")
continue_time = 0.02
stop_time = datetime.strptime(
    (buy_time + timedelta(minutes=continue_time)).strftime("%Y-%m-%d %H:%M:%S.%f"),
    "%Y-%m-%d %H:%M:%S.%f"
)
print(stop_time)
>>>2021-01-01 10:00:01.200000`
@flyhong666 测了下，设置为0.5甚至0.02都是可以的。0.5的话实际就是30s，0.02实际是1.2s。

2021-01-05 00:42 UTC, qianbilili commented
> 请问大佬，我同一台PC，切换账号，JdTdudfp的变量需要跟换吗，我看了下，切换账号后，这2个值是不变的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flyhong666"<notifications@github.com&gt;; 发送时间: 2021年1月4日(星期一) 上午10:48 收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412) 我的日子都是乱码，不知道咋回事 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flyhong666"<notifications@github.com&gt;; 发送时间: 2021年1月4日(星期一) 上午10:43 收件人: "huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送: "陈宇"<sff_chenyu@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [huanghyw/jd_seckill] 增加：自动停止软件运行的功能 (#412) 看了下日志，我的号都是出现90016，但是有一次出现90008。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 编码的问题，用utf 8 就可以看到了。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

他的算法和系统和浏览器有关,我的也一样,换了几个号都可以抢

2021-01-05 01:08 UTC, huanghyw approved these changes
多谢同学的代码贡献

2021-01-05 01:09 UTC, merged

2021-01-05 01:23 UTC, kevin-garrnet-hh commented
> 
> 
> 多谢同学的代码贡献

大佬..昨天docker都可以自动获取eid和fp，更新到今天的代码不行了...
![Uploading 图片.png…]()
卡在京东家电界面..后续加不上购物车

2021-01-05 02:21 UTC, TorrentialNight commented
我这运行过程中报这个错误能看下是什么问题吗
2021-01-05 10:00:20,064 - 13160-MainThread - D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py[line:621] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
2021-01-05 10:00:20,064 - 13160-MainThread - D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py[line:483] - INFO: 访问抢购订单结算页面...
2021-01-05 10:00:20,848 - 13160-MainThread - D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py[line:526] - INFO: 生成提交抢购订单所需参数...
2021-01-05 10:00:20,849 - 13160-MainThread - D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py[line:501] - INFO: 获取秒杀初始化信息...
2021-01-05 10:00:20,988 - 13160-MainThread - D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py[line:582] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
2021-01-05 10:00:20,989 - 13160-MainThread - D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py[line:483] - INFO: 访问抢购订单结算页面...
--- Logging error ---
Traceback (most recent call last):
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 362, in _seckill
    self.submit_seckill_order()
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 597, in submit_seckill_order
    headers=headers)
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\developer\env\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "D:\developer\env\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "D:\developer\env\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "D:\developer\env\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "D:\developer\env\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\developer\env\Python37\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "D:\developer\env\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\developer\env\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\developer\env\Python37\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 314, in new_func
    return func(self, *args, **kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 329, in seckill
    self._seckill()
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 364, in _seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
Arguments: (TooManyRedirects('Exceeded 30 redirects.'),)
--- Logging error ---
Traceback (most recent call last):
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 362, in _seckill
    self.submit_seckill_order()
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 597, in submit_seckill_order
    headers=headers)
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\PyCharm2019.2 work\jd_seckill-master\venv\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\developer\env\Python37\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "D:\developer\env\Python37\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "D:\developer\env\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "D:\developer\env\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "D:\developer\env\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "D:\developer\env\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\developer\env\Python37\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "D:\developer\env\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\developer\env\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\developer\env\Python37\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 314, in new_func
    return func(self, *args, **kwargs)
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 329, in seckill
    self._seckill()
  File "D:\PyCharm2019.2 work\jd_seckill-master\jd_spider_requests.py", line 364, in _seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
Arguments: (TooManyRedirects('Exceeded 30 redirects.'),)

2021-01-05 02:32 UTC, wrisin commented
> > 非docker环境无法获取`_JdTdudfp`的同学更新代码之后重新执行一次`pip install -r requirements.txt`，因为添加了新的三方包
> 
> 我Windows 10 ，安装的是python 3.9.1 ，这句话也执行过了。还是没法自动获取。

老哥，我也是相同环境，报错Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?咋整啊

2021-01-05 02:32 UTC, pxcoder commented
> > INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】为啥一直返回这儿？
> 
> +1

me too

2021-01-05 03:02 UTC, mrclock commented
今天有成功的兄die吗？

2021-01-05 06:10 UTC, lcyan commented
有京东会员综合评分下降的吗，用了几次掉到101了

2021-01-05 07:10 UTC, wanghlstar commented
> > cookies ~~ 能用手机验证码的，保留30天有效就好了~~不用每天扫码~~~ 就可以加个定时任务了~~~
> > today=`date '+%Y-%m-%d 09:59:59.500'`
> > last_day=`grep "09:59:59" config.ini | awk -F '= ' '{print $2}'`
> > sed -i '' "s/$last_day/$today/g" config.ini ###mac的 -i 需要加个''
> 
> 麻烦问下这个持续30天的cookies是网页版选择密码登录吗？网页版没有验证码登录

m.jd.com 用手机验证码登录~~

2021-01-05 07:30 UTC, wanghlstar commented on config.ini
> +continue_time = 5
cookie 的地方可以考虑换成用手机验证码登录的么？或者是说抢购页面换成手机版的m.jd.com，只要不再退出可以30天有效~~不用每天扫码~~~然后main.py 可以改成选择2， 就可以加个定时任务了，每天自动了~~~

2021-01-05 08:16 UTC, kevin-garrnet-hh commented
> 
> 
> 多谢同学的代码贡献

码主， 里面有人留微信.卖你的源码，你看是不是可以清理掉。
![图片](https://user-images.githubusercontent.com/42064410/103622142-39875000-4f71-11eb-845c-a77327adce33.png)

2021-01-05 13:06 UTC, wangxufire commented
> > > INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】为啥一直返回这儿？
> > 
> > 
> > +1
> 
> me too

@huanghyw 这个是啥原因

2021-01-05 13:09 UTC, Kethers commented
好像自从加了docker相关的代码之后，windows下用pycharm都不能直接打开二维码了（好像是因为路径名有空格），要去手动打开二维码扫，而且扫了之后会进到家用电器然后就没反应了？还好我当初fork了一个，今天是发现master里面有在更新才来重新clone，发现还是之前fork的能用（虽然不能自动停止预约），但这个更新的对windows直接用不了就很难受

2021-01-05 13:57 UTC, wanghuohuo0716 commented
> > > cookies ~~ 能用手机验证码的，保留30天有效就好了~~不用每天扫码~~~ 就可以加个定时任务了~~~
> > > today=`date '+%Y-%m-%d 09:59:59.500'`
> > > last_day=`grep "09:59:59" config.ini | awk -F '= ' '{print $2}'`
> > > sed -i '' "s/$last_day/$today/g" config.ini ###mac的 -i 需要加个''
> > 
> > 
> > 麻烦问下这个持续30天的cookies是网页版选择密码登录吗？网页版没有验证码登录
> 
> m.jd.com 用手机验证码登录~~

能方便发下是哪个响应的cookie么？麻烦问下，你这边是如何手动改cookie的呢？是复制cookie字符串，粘贴进去的么？还有大佬的cookie文件里面为啥是乱码，utf-8也不行，也不知道如何放在哪